spring:
  application:
   name: client-demo
  ai:
    mcp:
      client:
        name: mcp-client-demo
        sse:
          connections:
            server1:
              url: http://localhost:10080
        enabled: true
        type: sync
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:0.6b
        options:
          temperature: 0.7
server:
  port: 10081